### ISSUE TITLE
mistake in weight conversion 

### ISSUE THREAD

**Issue by xav01** [przemarbor/RUTMath#16]
Hi, 

I continue testing RUTMath. I found a problem in the weight conversion module :  the conversion between dag and kg is wrong. 
![Screenshot_2023-07-11-20-32-23-344_com hexbit rutmath](https://github.com/przemarbor/RUTMath/assets/30235797/50e17ab2-5776-49fd-b614-676a8268383d)

**Comment by przemarbor** [comment]
Fixed in release v0.1.4.
